name: Datadog Installation and configuration Pipeline
run-name: Datadog Installation and configuration Pipeline
on: [push]
env:
    CLUSTER_NAME: dockercoins-cluster-teo
    CLUSTER_ZONE: europe-west1-b
    PROJECT_NAME: teolia-school-devops
jobs:
    InstallAndConfigureDatadog:
        name: Install and configure Datadog in the GKE cluster.
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - name: Checkout repo
              uses: actions/checkout@master
            - name: Create Release
              id: create_release
              uses: actions/create-release@latest
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
              with:
                tag_name: ${{ vars.CURRENT_VERSION }}
                release_name: Release ${{ vars.CURRENT_VERSION }}
                body: |
                  App version ${{ vars.CURRENT_VERSION }}.
                draft: false
                prerelease: false
            - name: Install gcloud authentication plugin
              run: |
                REPO_URL="https://packages.cloud.google.com/apt"
                echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] $REPO_URL cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list >/dev/null
                curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

                sudo apt-get update -y
                sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

            - name: Authenticate to Google Cloud
              uses: 'google-github-actions/auth@v1'
              with:
                credentials_json: '${{ secrets.GCLOUD_KEY }}'
                token_format: 'access_token'

            - name: Authenticate to GKE cluster
              run: |   
                gcloud container clusters get-credentials \
                ${{ env.CLUSTER_NAME }} --zone ${{ env.CLUSTER_ZONE }} --project ${{ env.PROJECT_NAME }}
            - name: Install helm
              run : |
                curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
                chmod 700 get_helm.sh
                ./get_helm.sh
            - name: Update cluster name & datadog api key values in datadog-values.yml
              uses: cschleiden/replace-tokens@v1
              with:
                files: '["./datadog-values.yml"]'
                tokenPrefix: __
                tokenSuffix: __  
              env:
                DATADOG_API_KEY_SECRET: ${{ secrets.DATADOG_API_KEY_SECRET }}
                CLUSTER_NAME: ${{ env.CLUSTER_NAME }}
            - name: Deploy the datadog agent
              run: |
                helm repo add datadog https://helm.datadoghq.com
                helm repo update
                helm install datadog-${{ vars.CURRENT_VERSION }} --set datadog.site='datadoghq.com' --set datadog.apiKey=${{ secrets.DATADOG_API_KEY_SECRET }} datadog/datadog